### ISSUE TITLE
Missing repository: morfessor-dev

### ISSUE THREAD

**Issue by fcaldas** [aalto-speech/morfessor-demo#1]
Hi,

  I am currently trying to use morfessor-demo but I am having problems, the README.md says I should do a:
```
git submodule init
git submodule fetch
```
  To get all dependencies but one of them is `morfessor-dev` which no longer exists. 

Thanks in advance

**Comment by psmit** [comment]
Hi,

Morfessor-dev exists, but it is an internal repository. I don't think anyone has every tried the demo outside our group.

Using the public morfessor repository instead ( https://github.com/aalto-speech/morfessor ) should actually work nowadays. Please let me know if that gives any problems.

**Comment by fcaldas** [comment]
Hi @psmit ,

Thanks for the info, I was interested in the trained model used in the demo, but think I managed to obtain similar results after struggling a bit with morfessor-train.

Thanks,
